# Generated by Django 3.1 on 2022-09-28 04:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО контактного лица')),
                ('contact_value', models.CharField(max_length=255, verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=128, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип контакта',
                'verbose_name_plural': 'Типы контактов',
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=128, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип занятости',
                'verbose_name_plural': 'Типы занятости',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('position', models.CharField(blank=True, max_length=300, verbose_name='Должность')),
                ('city', models.CharField(blank=True, max_length=300, verbose_name='Город')),
                ('salary', models.CharField(blank=True, help_text='Пример: от 95 000 руб.', max_length=300, verbose_name='Зарплата')),
                ('short_description', models.CharField(blank=True, max_length=1000, verbose_name='Краткое описание')),
                ('requirements', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Требования')),
                ('conditions', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Условия')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='ФИО интервюера')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('contacts', models.ManyToManyField(to='garpix_vacancy.Contact', verbose_name='Контакты')),
                ('employment_types', models.ManyToManyField(to='garpix_vacancy.EmploymentType', verbose_name='Тип занятости')),
                ('tags', models.ManyToManyField(blank=True, to='garpix_vacancy.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Файл')),
                ('vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='garpix_vacancy.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='garpix_vacancy.contacttype', verbose_name='Тип контакта'),
        ),
    ]
